
(function(){
"use strict";
/*
  Presentation + local-assistant enhancement layer only.
  IMPORTANT: This file intentionally performs no MAV CWS requests.
  The proven app.js remains the sole owner of /cws/vtcfarm traffic.
*/
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const escapeHtml=v=>String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));

const KEY="MAV_VTC_FARM_MONITOR_UI_SETTINGS";
const DEFAULTS={appearance:"auto",logColorScheme:"mav",aiModelTier:"auto"};
const MODELS={
  compat:{id:"SmolLM2-135M-Instruct-ONNX-MHA",label:"Compatibility · 135M",short:"135M",dtype:"q8",tokens:110},
  balanced:{id:"SmolLM2-360M-Instruct-ONNX",label:"Balanced · 360M",short:"360M",dtype:"q8",tokens:130},
  quality:{id:"SmolLM2-1.7B-Instruct",label:"Quality · 1.7B",short:"1.7B",dtype:"q4f16",device:"webgpu",tokens:155}
};
const MODEL_ROOT="/ai/models/", MODEL_RUNTIME="/ai/vendor/transformers.min.js";
let settings=readSettings();
const ai={open:false,busy:false,status:"Knowledge mode · local model not loaded",generator:null,selected:null,loadPromise:null,messages:[],progress:0};

function readSettings(){try{const x={...DEFAULTS,...JSON.parse(localStorage.getItem(KEY)||"{}")};if(!["auto","day","night"].includes(x.appearance))x.appearance="auto";if(!["mav","vscode"].includes(x.logColorScheme))x.logColorScheme="mav";if(!["auto","compat","balanced","quality"].includes(x.aiModelTier))x.aiModelTier="auto";return x;}catch(_){return {...DEFAULTS};}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(settings));}catch(_){}applyTheme();renderSettings();}
function resolvedTheme(){if(settings.appearance!=="auto")return settings.appearance;const h=new Date().getHours();return h>=7&&h<19?"day":"night";}
function applyTheme(){document.body.dataset.siteTheme=resolvedTheme();document.body.dataset.logScheme=settings.logColorScheme||"mav";}
function status(text){ai.status=text;const a=$("#mfe-assistant-status"),b=$("#mfe-model-health");if(a)a.textContent=text;if(b)b.textContent=text;}
function modelLabel(){return settings.aiModelTier==="auto"?"Auto":(MODELS[settings.aiModelTier]?.label||settings.aiModelTier);}
function option(prop,value,title,desc,extra=""){const active=String(settings[prop])===String(value);return `<button class="mfe-setting-option ${active?"active":""}" data-mfe-setting="${prop}" data-mfe-choice="${value}"><b>${escapeHtml(title)}</b><small>${escapeHtml(desc)}</small>${extra}<span class="mfe-setting-check">✓</span></button>`;}
function card(title,desc,active,body,note){return `<article class="mfe-setting-card"><div class="mfe-setting-card-header"><div><h3>${escapeHtml(title)}</h3><p>${escapeHtml(desc)}</p></div><span class="mfe-setting-active">${escapeHtml(active)}</span></div><div class="mfe-setting-card-body">${body}${note?`<div class="mfe-setting-note">${escapeHtml(note)}</div>`:""}</div></article>`;}
function renderSettings(){
  const root=$("#mfe-settings-cards");if(!root)return;
  const appearance=settings.appearance==="auto"?`Auto · ${resolvedTheme()==="day"?"Day":"Night"} active`:`${settings.appearance==="day"?"Day":"Night"} active`;
  root.innerHTML=
    card("Appearance","Controls this monitor site only. Nothing is sent to the VTC Farm.",appearance,
      `<div class="mfe-setting-options">${option("appearance","day","Day","Use the light presentation at all times.")}${option("appearance","night","Night","Use the dark presentation at all times.")}${option("appearance","auto","Auto","Use Day from 07:00–19:00 and Night outside that window.")}</div>`,
      "Stored in localStorage on this browser only.")+
    card("Program Log Color Scheme","Choose the log palette independently from the site appearance. This changes presentation only; it never changes MAV log severity or capture.",settings.logColorScheme==="vscode"?"Visual Studio Code":"MAV",
      `<div class="mfe-setting-options">${option("logColorScheme","mav","MAV","MAV’s blue/green/gold diagnostic palette with Day and Night variants.",'<div class="mh-log-theme-preview mav"><span class="err">[Error]</span><span class="warn">[Warning]</span><span class="info">[Information]</span><span class="trace">[Trace]</span></div>')}${option("logColorScheme","vscode","Visual Studio Code","Visual Studio Code-inspired diagnostic colors with Light+ and Dark+ variants.",'<div class="mh-log-theme-preview vscode"><span class="err">[Error]</span><span class="warn">[Warning]</span><span class="info">[Information]</span><span class="trace">[Trace]</span></div>')}</div>`,
      "The selected palette is stored locally in this browser and applies only to the Program Log view.")+
    card("MAV Assistant Model","Use the same local inference tiers as MAV_MONITOR_UI. Auto chooses the best installed model that fits the browser.",modelLabel(),
      `<div class="mfe-setting-options">${option("aiModelTier","auto","Auto","Prefer the strongest installed local model supported by this browser.")}${option("aiModelTier","compat","Compatibility · 135M","Smallest model for constrained field laptops.")}${option("aiModelTier","balanced","Balanced · 360M","Better natural-language interpretation on ordinary modern laptops.")}${option("aiModelTier","quality","Quality · 1.7B","Largest local model. Intended for WebGPU-capable systems.")}</div><div class="mfe-inline-actions"><button id="mfe-load-model" class="monitor-tool-button">Load selected local model</button><span id="mfe-model-health" class="mfe-status">${escapeHtml(ai.status)}</span></div>`,
      "Models are loaded only from /ai/models on the processor. Remote model downloads are disabled.")+
    card("Assistant Grounding","The assistant uses only information already rendered by this working Farm monitor. It does not add CWS calls or change Farm behavior.","Read only",
      `<div class="mfe-setting-options"><div class="mfe-setting-option active" style="cursor:default"><b>Current monitor evidence</b><small>Overview, active alerts, device inventory, routes, and browser log text already present in this page.</small><span class="mfe-setting-check">✓</span></div><div class="mfe-setting-option active" style="cursor:default"><b>No CWS actions</b><small>This enhancement pass is observation/troubleshooting only.</small><span class="mfe-setting-check">✓</span></div><div class="mfe-setting-option active" style="cursor:default"><b>No cloud</b><small>Chat stays in browser memory unless you explicitly export it.</small><span class="mfe-setting-check">✓</span></div></div>`,
      "The original app.js remains the only component that communicates with /cws/vtcfarm.")+
    card("Local Data","Site preferences persist locally. Assistant conversation does not persist across page reloads unless you export it.","Browser local",
      `<div class="mfe-setting-options"><div class="mfe-setting-option active" style="cursor:default"><b>Preferences</b><small>Appearance, program log color scheme, and model tier use localStorage.</small><span class="mfe-setting-check">✓</span></div><div class="mfe-setting-option active" style="cursor:default"><b>Conversation</b><small>Held in memory for this page session only.</small><span class="mfe-setting-check">✓</span></div><div class="mfe-setting-option active" style="cursor:default"><b>Manual export only</b><small>A chat file is created only when you press Export.</small><span class="mfe-setting-check">✓</span></div></div>`,
      "Nothing in this settings page changes SystemDefinition or processor configuration.");
}
function addAssistantDom(){
  if($("#mfe-assistant"))return;
  const wrapper=document.createElement("div");
  wrapper.innerHTML=`<button id="mfe-assistant-edge" class="mfe-assistant-edge" type="button" aria-label="Open MAV VTC Farm Troubleshooter"><span>✦</span><b>AI</b></button>
  <aside id="mfe-assistant" class="mfe-assistant" aria-label="MAV VTC Farm Troubleshooter" aria-hidden="true">
    <header class="mfe-assistant-header"><div class="mfe-assistant-title"><span class="mfe-assistant-mark">✦</span><div><strong>MAV VTC Farm Advisor</strong><small id="mfe-assistant-status">Knowledge mode · local model not loaded</small></div></div><div class="mfe-assistant-header-actions"><button id="mfe-export-chat" class="mfe-icon-button">Export</button><button id="mfe-clear-chat" class="mfe-icon-button">Clear</button><button id="mfe-close-chat" class="mfe-icon-button" aria-label="Close">×</button></div></header>
    <div id="mfe-assistant-context" class="mfe-assistant-context"></div>
    <div id="mfe-chat-messages" class="mfe-assistant-messages" aria-live="polite"></div>
    <div id="mfe-ai-progress" class="mfe-ai-progress" hidden><div class="mfe-ai-progress-head"><strong id="mfe-ai-progress-stage">Working…</strong><span id="mfe-ai-progress-pct">0%</span></div><div class="mfe-ai-progress-track"><div id="mfe-ai-progress-bar" class="mfe-ai-progress-bar"></div></div></div>
    <div class="mfe-prompt-chips"><button data-mfe-suggestion="What is the health of the VTC Farm?">Farm health</button><button data-mfe-suggestion="Run the VTC Farm regression tests">Regression tests</button><button data-mfe-suggestion="What NVX issues are visible?">NVX health</button><button data-mfe-suggestion="Summarize the active alerts">Active alerts</button><button data-mfe-suggestion="Summarize the configured inventory">Inventory</button><button data-mfe-suggestion="What should I check first in the field?">Field check</button></div>
    <footer class="mfe-assistant-footer"><div class="mfe-composer"><textarea id="mfe-ai-input" rows="2" placeholder="Ask about Farm health, NVX devices, routes, alerts, or visible evidence…"></textarea><button id="mfe-send" class="mfe-send">Ask</button></div><div class="mfe-assistant-footnote">Local inference (/ai) · current Farm monitor evidence · no cloud · no CWS actions</div></footer>
  </aside>`;
  document.body.append(...wrapper.children);
}
function toggle(force){ai.open=typeof force==="boolean"?force:!ai.open;$("#mfe-assistant")?.classList.toggle("is-open",ai.open);$("#mfe-assistant")?.setAttribute("aria-hidden",ai.open?"false":"true");$("#mfe-assistant-edge")?.classList.toggle("is-hidden",ai.open);$("#monitor-assistant-button")?.classList.toggle("is-active",ai.open);document.body.classList.toggle("mfe-assistant-open",ai.open);if(ai.open){renderChat();refreshAssistantContext();setTimeout(()=>$("#mfe-ai-input")?.focus(),100);}}
function nowTime(){return new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false});}
function normalizeText(value){return String(value||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function compactText(value,max=1200){return String(value||"").replace(/\s+/g," ").trim().slice(0,max);}
function copyChatText(text,button){const value=String(text||"");const done=()=>{if(!button)return;button.classList.add("copied");button.setAttribute("aria-label","Copied");setTimeout(()=>{button.classList.remove("copied");button.setAttribute("aria-label","Copy message");},1000);};if(navigator.clipboard?.writeText){navigator.clipboard.writeText(value).then(done).catch(()=>{});return;}const area=document.createElement("textarea");area.value=value;area.style.position="fixed";area.style.opacity="0";document.body.appendChild(area);area.select();try{document.execCommand("copy");done();}catch(_){}area.remove();}
function sourceKind(message){if(message.sourceKind)return message.sourceKind;const p=String(message.parser||"").toLowerCase();if(p.includes("local")&&!p.includes("fallback"))return "hybrid";return "knowledge";}
function sourceBadgeHtml(message){const kind=sourceKind(message),label=kind==="hybrid"?"MAV Knowledge + AI":kind==="ai"?"Local AI":"MAV Knowledge";return `<div class="mfe-response-meta"><span class="mfe-source-badge ${kind}">${escapeHtml(label)}</span></div>`;}
function interpretationTraceHtml(trace,forceOpen=false){if(!trace)return "";const parsed=trace.parsedIntent||{};const row=(label,value)=>value===undefined||value===null||String(value)===""?"":`<div class="mfe-trace-row"><span class="mfe-trace-label">${escapeHtml(label)}</span><span class="mfe-trace-value">${escapeHtml(String(value))}</span></div>`;const raw=String(trace.rawOutput||"").trim(),parsedJson=JSON.stringify(parsed,null,2);const meta=[trace.modelLabel||"MAV Knowledge",trace.intent||parsed.intent||"interpretation"].filter(Boolean).join(" · ");return `<div class="mfe-trace-message"><details class="mfe-interpretation-trace" ${forceOpen?"open":""}><summary><span class="mfe-trace-summary-main"><span class="mfe-trace-dot" aria-hidden="true"></span><span>Interpretation details</span></span><span class="mfe-trace-summary-meta">${escapeHtml(meta)}</span></summary><div class="mfe-trace-body"><div class="mfe-trace-note">How the request was classified before MAV Knowledge selected the evidence used for this answer.</div>${row("Request mode",trace.requestMode)}${row("Intent",trace.intent||parsed.intent)}${row("Target",trace.target||parsed.target||"—")}${row("Evidence scope",trace.scope)}${row("Parser",trace.parser)}${row("Routing",trace.route)}${row("Outcome",trace.outcome)}<details class="mfe-trace-subdetails"><summary>Parsed request</summary><pre>${escapeHtml(parsedJson)}</pre></details>${raw?`<div class="mfe-trace-block"><div class="mfe-trace-block-title">Local parser output</div><pre>${escapeHtml(raw)}</pre></div>`:""}</div></details></div>`;}
function assistantContextHtml(){
 const health=compactText($("#overview-health")?.textContent||"Unknown",80),cws=compactText($("#overview-cws")?.textContent||"Unknown",80);
 const alerts=$$(".alert-card").filter(card=>/active/i.test(card.querySelector(".alert-state")?.textContent||"Active")&&!/resolved/i.test(card.querySelector(".alert-state")?.textContent||""));
 const assigned=$$(".farm-codec-card").filter(card=>/assigned/i.test(card.textContent||"")).length;
 const contextPill=(label,value,tone="")=>`<div class="mfe-context-pill ${tone}"><span>${escapeHtml(label)}</span><strong>${escapeHtml(String(value))}</strong></div>`;
 return `<div class="mfe-context-head"><span>LIVE FARM CONTEXT</span><small>Read-only evidence already visible in this monitor</small></div><div class="mfe-context-grid">${contextPill("Farm",health,/online|healthy/i.test(health)?"good":"")}${contextPill("CWS",cws,/online/i.test(cws)?"good":"")}${contextPill("Active alerts",alerts.length,alerts.length?"warn":"good")}${contextPill("Assigned codecs",assigned)}</div>`;
}
function refreshAssistantContext(){const root=$("#mfe-assistant-context");if(root)root.innerHTML=assistantContextHtml();}

function renderChat(){
 const root=$("#mfe-chat-messages");if(!root)return;refreshAssistantContext();
 if(!ai.messages.length){root.innerHTML=`<div class="mfe-welcome"><div class="mfe-welcome-icon">✦</div><div><strong>Ask me what the field technician should do next.</strong><p>I’ll correlate the live Farm state, alerts, codec reservations, NVX evidence, routes, and recent logs already visible in this monitor.</p></div></div><div class="mfe-welcome-rules"><span>Read only</span><span>Evidence grounded</span><span>Local model optional</span></div>`;return;}
 root.innerHTML=ai.messages.map((m,index)=>{
   if(m.role==="user")return `<article class="mfe-message user has-copy"><button type="button" class="mfe-copy-button" data-mfe-copy="${index}" aria-label="Copy message"><span class="mfe-copy-icon"></span></button><span class="who">You</span><div class="answer">${escapeHtml(m.text||"")}</div><div class="micro">${m.time?escapeHtml(m.time):""}</div></article>`;
   const trace=m.interpretation?interpretationTraceHtml(m.interpretation,false):"";
   const evidence=m.evidence?.length?`<details class="mfe-evidence"><summary><span>Evidence used</span><b>${m.evidence.length}</b></summary><div class="mfe-evidence-list">${m.evidence.map(e=>`<div class="mfe-evidence-item"><span>${escapeHtml(String(e.kind||"evidence").toUpperCase())}</span><div>${escapeHtml(String(e.id||""))}${e.id?" · ":""}${escapeHtml(String(e.text||""))}</div></div>`).join("")}</div>${m.parser?`<div class="mfe-evidence-meta">Request interpretation: ${escapeHtml(m.parser)}</div>`:""}</details>`:"";
   return `<article class="mfe-message assistant has-copy"><button type="button" class="mfe-copy-button" data-mfe-copy="${index}" aria-label="Copy message"><span class="mfe-copy-icon"></span></button><div class="mfe-assistant-answer-head"><span class="who">MAV VTC Farm Advisor</span>${sourceBadgeHtml(m)}</div>${m.tag?`<div class="mfe-answer-title">${escapeHtml(m.tag)}</div>`:""}<div class="answer">${escapeHtml(m.text||"")}</div><div class="mfe-answer-support">${evidence}${trace}</div><div class="micro">${escapeHtml(m.source||"MAV Knowledge")}${m.time?" · "+escapeHtml(m.time):""}</div></article>`;
 }).join("");
 root.querySelectorAll("[data-mfe-copy]").forEach(button=>button.onclick=()=>{const message=ai.messages[Number(button.dataset.mfeCopy)];if(message)copyChatText(message.text,button);});root.scrollTop=root.scrollHeight;
}
function progress(value,stage){ai.progress=Math.max(0,Math.min(100,Number(value)||0));const wrap=$("#mfe-ai-progress");if(!wrap)return;wrap.hidden=value<=0;$("#mfe-ai-progress-bar").style.width=ai.progress+"%";$("#mfe-ai-progress-pct").textContent=Math.round(ai.progress)+"%";$("#mfe-ai-progress-stage").textContent=stage||"Working…";}
async function withTimeout(promise,timeoutMs,label){let timer;const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>{const e=new Error(`${label||"Operation"} timed out after ${Math.round(timeoutMs/1000)}s`);e.name="MAVTimeoutError";reject(e);},timeoutMs);});return Promise.race([Promise.resolve(promise),timeout]).finally(()=>clearTimeout(timer));}
async function modelPack(model){const c=new AbortController(),t=setTimeout(()=>c.abort(),3500);try{return await fetch(MODEL_ROOT+model.id+"/config.json",{cache:"no-store",signal:c.signal}).then(r=>r.ok).catch(()=>false);}finally{clearTimeout(t);}}
async function selectModel(){if(settings.aiModelTier!=="auto"){const m=MODELS[settings.aiModelTier];if(m.device==="webgpu"&&!navigator.gpu)throw new Error(m.label+" requires WebGPU.");if(!await modelPack(m))throw new Error(m.label+" is not installed under /ai/models.");return m;}const available={};for(const k of ["quality","balanced","compat"])available[k]=await modelPack(MODELS[k]);const cores=Number(navigator.hardwareConcurrency||0),mem=Number(navigator.deviceMemory||0);if(available.quality&&navigator.gpu&&cores>=8&&(!mem||mem>=8))return MODELS.quality;if(available.balanced&&cores>=4&&(!mem||mem>=4))return MODELS.balanced;if(available.compat)return MODELS.compat;if(available.balanced)return MODELS.balanced;if(available.quality&&navigator.gpu)return MODELS.quality;throw new Error("No compatible local model pack is installed under /ai/models.");}
async function loadModel(){const desired=await withTimeout(selectModel(),7000,"Local model selection");if(ai.generator&&ai.selected?.id===desired.id)return ai.generator;if(ai.loadPromise)return ai.loadPromise;if(ai.generator){try{await Promise.race([Promise.resolve(ai.generator.dispose?.()),new Promise(r=>setTimeout(r,1200))]);}catch(_){}ai.generator=null;}status("Loading "+desired.label+"…");progress(18,"Loading local AI runtime…");ai.loadPromise=(async()=>{try{const module=await withTimeout(import(MODEL_RUNTIME),7000,"Local AI runtime load"),{env,pipeline}=module;env.allowLocalModels=true;env.allowRemoteModels=false;env.localModelPath=MODEL_ROOT;env.backends.onnx.wasm.wasmPaths={mjs:new URL("/ai/vendor/ort-wasm-simd-threaded.jsep.js",location.href).href,wasm:new URL("/ai/vendor/ort-wasm-simd-threaded.jsep.wasm",location.href).href};env.backends.onnx.wasm.numThreads=1;env.backends.onnx.wasm.proxy=true;const generator=await withTimeout(pipeline("text-generation",desired.id,{dtype:desired.dtype,...(desired.device?{device:desired.device}:{}),progress_callback:p=>{if(p&&p.status==="progress"&&p.total){const pc=Math.max(0,Math.min(100,p.loaded/p.total*100));status("Loading "+desired.label+" · "+Math.round(pc)+"%");progress(24+pc*.5,"Loading "+desired.short+" · "+Math.round(pc)+"%");}}}),45000,"Local model initialization");ai.generator=generator;ai.selected=desired;status("Local model ready · "+desired.short);progress(78,"Local model ready · "+desired.short);return generator;}catch(error){status("Knowledge mode · "+String(error.message||error));throw error;}finally{ai.loadPromise=null;}})();return ai.loadPromise;}
function evidenceRecords(){
 const records=[];const put=(kind,id,text)=>{text=compactText(text,1800);if(text)records.push({kind,id:String(id||records.length+1),text});};
 const health=$("#overview-health")?.textContent,healthDetail=$("#overview-health-detail")?.textContent,cws=$("#overview-cws")?.textContent,cwsDetail=$("#overview-cws-detail")?.textContent,topology=$("#overview-dsp")?.textContent,topologyDetail=$("#overview-dsp-detail")?.textContent,config=$("#overview-config")?.textContent,configDetail=$("#overview-config-detail")?.textContent;
 put("health","monitor",`${health||"Unknown"}. ${healthDetail||""}`);put("cws","vtcfarm",`${cws||"Unknown"}. ${cwsDetail||""}`);put("topology","farm",`${topology||"Unknown"}. ${topologyDetail||""}`);put("configuration","definition",`${config||"Unknown"}. ${configDetail||""}`);
 $$(".alert-card").forEach((card,i)=>{const sev=compactText(card.querySelector(".alert-severity")?.textContent,80),device=compactText(card.querySelector(".alert-device")?.textContent,160),title=compactText(card.querySelector("h3")?.textContent,240),detail=compactText(card.querySelector(".alert-content p")?.textContent,600),stateText=compactText(card.querySelector(".alert-state")?.textContent,80);put("alert",device||String(i+1),`${sev} ${device}: ${title}. ${detail} State=${stateText}`);});
 $$(".device-card").forEach((card,i)=>{const name=compactText(card.querySelector("h3")?.textContent,220),category=compactText(card.querySelector(".device-category")?.textContent,100),statusText=compactText(card.querySelector(".health-mini")?.textContent,120),summary=compactText(card.querySelector(".device-card-summary")?.textContent,800);put("device",name||String(i+1),`${category} ${name}. ${statusText}. ${summary}`);});
 $$(".route-item").forEach((item,i)=>put("route",String(i+1),item.textContent));
 $$(".log-row").slice(0,20).forEach((row,i)=>put("log",String(i+1),row.textContent));
 if($("[data-view='commands']")){put("commands","farm","Farm command UI exposes reserve, release, re-route streams, dial, hang up, answer, DTMF, presentation on/off, self view on/off, and NVX video source-to-destination routing when the corresponding CWS capability is available.");}
 return records;
}
function deviceNames(){return $$(".device-card h3").map(x=>String(x.textContent||"").trim()).filter(Boolean);}
function resolveTarget(question){const q=normalizeText(question);let best="",score=0;for(const name of deviceNames()){const n=normalizeText(name);if(!n)continue;let s=0;if(q.includes(n))s=100+n.length;else{const words=n.split(" ").filter(x=>x.length>2),hits=words.filter(w=>q.includes(w)).length;if(hits>=2)s=20+hits*10;}if(s>score){score=s;best=name;}}return best;}

function isFarmRegressionRequest(question){
 const q=normalizeText(question);
 return /\b(run|perform|execute|start)\b.*\b(regression|regression test|regression tests|test suite)\b/.test(q)
   || /\b(regression|regression test|regression tests)\b.*\b(run|test|check)\b/.test(q);
}
async function runVtcFarmRegression(){
 status("Running VTC Farm regression tests…");progress(20,"Invoking Farm-native regression suite…");
 const response=await farmCws("/system/vtcfarm/regression","POST",{});
 const value=farmValue(response)||{},checks=arr(value.Checks||value.checks);
 const pass=Number(value.Pass??value.pass??0),fail=Number(value.Fail??value.fail??0),warn=Number(value.Warn??value.warn??0);
 progress(100,"VTC Farm regression complete");status(`Regression complete · ${pass} PASS · ${fail} FAIL · ${warn} WARN`);
 return {text:`VTC Farm regression finished: ${pass} passed, ${fail} failed, ${warn} warned.`,tag:`${pass} PASS · ${fail} FAIL · ${warn} WARN`,source:"VTC Farm native regression",evidence:checks.map((x,i)=>({kind:"test",id:`#${i+1}`,text:`[${x.Status||x.status}] ${x.Name||x.name}: ${x.Detail||x.detail}`})),results:checks};
}

function classifyIntent(question){const q=normalizeText(question);if(/\b(regression|regression test|regression tests|test suite)\b/.test(q))return "regression";if(/\b(command|commands|control|controls|what can i do|available cws)\b/.test(q))return "commands";if(/\b(field|check first|what should i check|diagnose first|troubleshoot first)\b/.test(q))return "field_check";if(/\b(alert|alerts|warning|warnings|error|errors|issue|issues)\b/.test(q))return "alerts";if(/\b(route|routing|stream|streams|rtsp|signal path)\b/.test(q))return "routes";if(/\b(inventory|configured devices|device inventory|how many|encoder|decoder|nvx)\b/.test(q))return "inventory";if(/\b(health|healthy|status|online|responding|cws)\b/.test(q))return resolveTarget(question)?"device_status":"health";if(resolveTarget(question))return "device_status";return "general";}
function directInterpretation(question){const intent=classifyIntent(question),target=resolveTarget(question);if(intent!=="general")return {intent,target,reason:"Deterministic Farm terminology matched the request"};return null;}
async function interpretQuestion(question){
 const direct=directInterpretation(question),fallback={intent:classifyIntent(question),target:resolveTarget(question)};if(direct)return {intent:direct.intent,target:direct.target,source:"MAV deterministic interpretation",trace:{modelLabel:"MAV Knowledge",requestMode:"Troubleshooting",intent:direct.intent,target:direct.target,scope:direct.target?`Farm evidence for ${direct.target}`:"VTC Farm monitor evidence",parser:"Deterministic MAV interpretation",route:"Request → MAV Knowledge → Farm evidence",outcome:direct.reason,parsedIntent:{intent:direct.intent,target:direct.target}}};
 if(!ai.generator){try{await loadModel();}catch(_){return {...fallback,source:"MAV deterministic interpretation · local model unavailable",trace:{modelLabel:"MAV Knowledge",requestMode:"Troubleshooting",intent:fallback.intent,target:fallback.target,scope:"VTC Farm monitor evidence",parser:"Deterministic MAV recovery; local model unavailable",route:"MAV Knowledge → Farm evidence",outcome:"Recovered intent used for grounded answer",parsedIntent:fallback}};}}
 let rawOutput="";try{const names=deviceNames().slice(0,40);const prompt=`You are an intent parser for the MAV VTC Farm monitor. Return ONLY one compact JSON object with keys intent and target. Allowed intents: health, alerts, inventory, routes, commands, regression, field_check, device_status, general. target must be an exact configured device name from the list when the user refers to one, otherwise empty string. Do not answer the user.\n\nCONFIGURED DEVICE NAMES:\n${names.join("\n")}\n\nUSER QUESTION:\n${question}\n\nJSON:`;const r=await withTimeout(ai.generator(prompt,{max_new_tokens:ai.selected?.tokens||120,do_sample:false,temperature:0,return_full_text:false}),16000,"Local AI interpretation");rawOutput=String(r?.[0]?.generated_text||"").trim();const match=rawOutput.match(/\{[\s\S]*?\}/),parsed=match?JSON.parse(match[0]):{};const allowed=new Set(["health","alerts","inventory","routes","commands","regression","field_check","device_status","general"]);const intent=allowed.has(String(parsed.intent||"").toLowerCase())?String(parsed.intent).toLowerCase():fallback.intent;const target=deviceNames().find(n=>normalizeText(n)===normalizeText(parsed.target))||fallback.target;return {intent,target,source:"Local "+ai.selected.short+" interpretation + MAV validation",trace:{modelLabel:"Local model · "+ai.selected.short,requestMode:"Troubleshooting",intent,target,scope:target?`Farm evidence for ${target}`:"VTC Farm monitor evidence",parser:"Structured JSON from local model + MAV validation",route:"Local AI → MAV Knowledge → Farm evidence",outcome:"Evidence scope selected for grounded troubleshooting answer",rawOutput,parsedIntent:{intent,target}}};}catch(error){return {...fallback,source:"MAV deterministic interpretation · local model fallback",trace:{modelLabel:"Local model · recovered",requestMode:"Troubleshooting",intent:fallback.intent,target:fallback.target,scope:"VTC Farm monitor evidence",parser:"MAV deterministic recovery after local-model parser failure",route:"Local parser fallback → MAV Knowledge → Farm evidence",outcome:"Recovered intent used for grounded troubleshooting answer",rawOutput,parsedIntent:fallback}};}
}
function recordsBy(kind,records){return records.filter(x=>x.kind===kind);}
function activeAlertRecords(records){return recordsBy("alert",records).filter(x=>/\bactive\b/i.test(x.text)&&!/\bresolved\b/i.test(x.text));}
function answerFromKnowledge(question,parsed){const records=evidenceRecords(),intent=parsed.intent,target=parsed.target,e=[];const add=(r)=>{if(r&&!e.includes(r))e.push(r);};const health=records.find(x=>x.kind==="health"),cws=records.find(x=>x.kind==="cws"),topology=records.find(x=>x.kind==="topology"),config=records.find(x=>x.kind==="configuration"),alerts=activeAlertRecords(records),devices=recordsBy("device",records),routes=recordsBy("route",records),logs=recordsBy("log",records);
 if(intent==="health"){[health,cws,topology,config,...alerts.slice(0,3)].forEach(add);const warningCount=alerts.filter(x=>/warning/i.test(x.text)).length;return {text:`${health?.text||"Farm monitoring state is unknown."}\n${cws?.text||"CWS state is unknown."}\n${topology?.text||"Topology is not currently visible."}\n${alerts.length?`MAV currently sees ${alerts.length} active alert${alerts.length===1?"":"s"}${warningCount?`, including ${warningCount} warning${warningCount===1?"":"s"}`:""}.`:"No active monitor-side alerts are currently visible."}`,evidence:e,source:"MAV Knowledge + Farm evidence",tag:"Farm health"};}
 if(intent==="alerts"){alerts.slice(0,12).forEach(add);if(!alerts.length){[health,cws].forEach(add);return {text:"MAV does not currently show any active Farm monitor alerts.",evidence:e,source:"MAV Knowledge + Farm evidence",tag:"Active alerts"};}const lines=alerts.map(x=>`• ${x.text.replace(/\s*State=.*$/i,"")}`).slice(0,8);return {text:`MAV currently sees ${alerts.length} active Farm alert${alerts.length===1?"":"s"}:\n${lines.join("\n")}${alerts.length>8?`\n• …and ${alerts.length-8} more.`:""}`,evidence:e,source:"MAV Knowledge + Farm evidence",tag:"Active alerts"};}
 if(intent==="inventory"){[topology,...devices.slice(0,12)].forEach(add);const names=devices.map(x=>x.id).filter(Boolean);return {text:`${topology?.text||`MAV currently sees ${devices.length} configured Farm devices.`}\nConfigured devices include: ${names.slice(0,16).join(", ")}${names.length>16?`, and ${names.length-16} more`:""}.`,evidence:e,source:"MAV Knowledge + SystemDefinition evidence",tag:"Configured inventory"};}
 if(intent==="routes"){routes.slice(0,12).forEach(add);logs.filter(x=>/route|stream|rtsp/i.test(x.text)).slice(0,8).forEach(add);if(!e.length){alerts.filter(x=>/rtsp|stream|route/i.test(x.text)).slice(0,8).forEach(add);return {text:e.length?`I do not see a complete live route table in the Farm monitor, but MAV does see route/stream-related conditions. The current evidence is attached below.`:"The Farm monitor does not currently expose enough live route evidence to prove an active signal path. I would verify the relevant encoder RTSP URL, destination selection, and recent Farm logs before concluding the route is good or bad.",evidence:e,source:"MAV Knowledge + Farm evidence",tag:"Route evidence"};}return {text:`Current Farm route evidence is available. I found ${e.length} route/log record${e.length===1?"":"s"} relevant to the request; review the evidence below for the actual source/destination and stream values rather than inferring state from configuration alone.`,evidence:e,source:"MAV Knowledge + Farm evidence",tag:"Route evidence"};}
 if(intent==="commands"){const cmd=records.find(x=>x.kind==="commands");add(cmd);return {text:"The Farm command surface exposed by this monitor includes codec reserve/release, re-route streams, dial, hang up, answer, DTMF, presentation on/off, self-view on/off, and NVX video source-to-destination routing. These are explicit operator actions; MAV should not issue them just because a troubleshooting question mentions one.",evidence:e,source:"MAV Knowledge + CWS command surface",tag:"Available CWS actions"};}
 if(intent==="field_check"){[cws,...alerts.slice(0,5),...logs.filter(x=>/error|warn|fail|offline|timeout/i.test(x.text)).slice(0,4)].forEach(add);let text="Start with the evidence that can invalidate the most assumptions:\n1. Confirm VTC Farm CWS is online and the definition heartbeat is current.\n";if(alerts.length)text+=`2. Resolve the active monitor warnings first — MAV currently sees ${alerts.length}.\n`;else text+="2. Confirm there are no active Farm monitor alerts.\n";text+="3. Verify the target encoder has a real RTSP location and the intended decoder is selected.\n4. Then inspect the latest Farm logs for route, timeout, or device-response evidence before changing programming.";return {text,evidence:e,source:"MAV Knowledge + Farm evidence",tag:"Field diagnosis"};}
 if(intent==="device_status"&&target){const targetNorm=normalizeText(target),device=devices.find(x=>normalizeText(x.id)===targetNorm),relatedAlerts=alerts.filter(x=>normalizeText(x.id)===targetNorm||normalizeText(x.text).includes(targetNorm)),relatedLogs=logs.filter(x=>normalizeText(x.text).includes(targetNorm)).slice(0,5);[device,...relatedAlerts,...relatedLogs].forEach(add);if(!device)return {text:`I recognize ${target} as the requested target, but I do not have a current device card for it in the Farm evidence.`,evidence:e,source:"MAV Knowledge + Farm evidence",tag:"Device status"};return {text:`For ${target}, MAV currently has this configured/observed evidence:\n${device.text}${relatedAlerts.length?`\nThere ${relatedAlerts.length===1?"is":"are"} ${relatedAlerts.length} active alert${relatedAlerts.length===1?"":"s"} tied to this device.`:"\nNo active Farm monitor alert is currently tied directly to this device."}${relatedLogs.length?`\nI also found ${relatedLogs.length} recent log record${relatedLogs.length===1?"":"s"} mentioning it.`:""}`,evidence:e,source:"MAV Knowledge + Farm evidence",tag:"Device status"};}
 [health,cws,topology,...alerts.slice(0,4)].forEach(add);return {text:"I can ground answers in the VTC Farm monitor’s current health, alerts, configured NVX inventory, route evidence, logs, and explicit CWS command surface. I do not have enough evidence to answer that question more specifically without inventing state; name the device, route, alert, or symptom you want to troubleshoot.",evidence:e,source:"MAV Knowledge + Farm evidence",tag:"Evidence limited"};}
async function ask(text){text=String(text||"").trim();if(!text||ai.busy)return;$("#mfe-ai-input").value="";ai.messages.push({role:"user",text,time:nowTime()});renderChat();ai.busy=true;$("#mfe-send").disabled=true;status("Gathering relevant MAV evidence…");progress(8,"Reading current Farm evidence…");try{
if(isFarmRegressionRequest(text)){
  const result=await runVtcFarmRegression();
  ai.messages.push({role:"assistant",text:result.text,evidence:result.evidence,source:result.source,tag:result.tag,time:nowTime(),action:true,
    trace:{modelLabel:"MAV deterministic action",requestMode:"Regression",intent:"regression",target:"VTC Farm",scope:"Live VTC Farm CWS regression suite",parser:"Deterministic command routing",route:"User request → VTC Farm regression runner → live CWS evidence",outcome:result.tag,parsedIntent:{intent:"regression",target:"VTC Farm"}}});
  if(ai.messages.length>100)ai.messages.splice(0,ai.messages.length-100);
  renderChat();
  return;
}
progress(25,"Classifying troubleshooting request…");const direct=directInterpretation(text);if(!direct&&!ai.generator){progress(32,"Preparing local interpreter…");try{await loadModel();}catch(_){progress(58,"Local model unavailable · continuing with MAV Knowledge");}}progress(62,direct?"Deterministic MAV interpretation resolved":"Interpreting request locally…");const parsed=await interpretQuestion(text);progress(84,"Correlating Farm health, alerts, devices, routes and logs…");const answer=answerFromKnowledge(text,parsed);progress(96,"Formatting grounded troubleshooting answer…");ai.messages.push({role:"assistant",text:answer.text,evidence:answer.evidence||[],source:answer.source,sourceKind:/^Local\s/i.test(parsed.source||"")&&!/fallback/i.test(parsed.source||"")?"hybrid":"knowledge",parser:parsed.source,tag:answer.tag,time:nowTime(),interpretation:parsed.trace||null});if(ai.messages.length>100)ai.messages.splice(0,ai.messages.length-100);}catch(error){ai.messages.push({role:"assistant",text:"I couldn’t complete that request. "+String(error.message||error),source:"MAV VTC Farm Troubleshooter",sourceKind:"knowledge",tag:"Request failed",time:nowTime()});}finally{ai.busy=false;$("#mfe-send").disabled=false;progress(100,"Complete");status(ai.generator?"Local model ready · "+ai.selected.short:"Knowledge mode · local model not loaded");setTimeout(()=>progress(0),650);renderChat();}}
function farmExportSafePart(value){return String(value||'').trim().replace(/[^a-z0-9._-]+/gi,"_").replace(/^_+|_+$/g,"").slice(0,80)||"VTC_Farm";}
function farmChatExportFilename(){const stamp=new Date().toISOString().replace(/[:]/g,"-").replace(/\.\d{3}Z$/,"");return `MAV_VTC_Farm_Assistant_Chat_${farmExportSafePart("VTC_Farm")}_${stamp}.html`;}
function farmExportTheme(){return document.body.dataset.siteTheme||settings.appearance||"day";}
function farmBuildChatExportHtml(){
 const exported=new Date(),theme=farmExportTheme(),model=ai.selected?.short||MODELS[settings.aiModelTier]?.label||"Knowledge mode";
 const cwsRoot="/cws/vtcfarm";
 const messages=ai.messages.length?ai.messages.map(m=>`${m.role==="assistant"&&m.interpretation?interpretationTraceHtml(m.interpretation,true):""}<article class="chat-message ${m.role}"><div class="chat-who">${m.role==="user"?"You":"MAV VTC Farm Troubleshooter"}</div>${m.role==="assistant"?sourceBadgeHtml(m):""}<div class="chat-answer">${escapeHtml(m.text||"")}</div>${m.tag&&m.role==="assistant"?`<span class="mfe-answer-tag">${escapeHtml(m.tag)}</span>`:""}${m.evidence?.length?`<details class="mfe-evidence" open><summary>Why I’m saying that · ${m.evidence.length} evidence record${m.evidence.length===1?"":"s"}</summary>${m.evidence.map(e=>`<div class="mfe-evidence-item">${escapeHtml(String(e.kind||"evidence").toUpperCase()+" "+String(e.id||"")+" · "+String(e.text||""))}</div>`).join("")}${m.parser?`<div class="mfe-evidence-meta">Interpretation: ${escapeHtml(m.parser)}</div>`:""}</details>`:""}${m.role==="assistant"?`<div class="chat-meta">${escapeHtml(m.source||"MAV Knowledge")}${m.time?" · "+escapeHtml(m.time):""}</div>`:""}</article>`).join(""):`<div class="chat-empty">No chat messages were present when this export was created.</div>`;
 const palette=theme==="day"?`:root{--bg:#eef3f8;--panel:#fff;--panel2:#f4f7fb;--border:#c9d5e2;--text:#172231;--muted:#42566b;--blue:#0969da;--green:#1f883d;--user:#dcebf8;--shadow:rgba(37,58,78,.08)}`:`:root{--bg:#071421;--panel:#102638;--panel2:#142d42;--border:rgba(132,188,229,.18);--text:#f3f8fc;--muted:#8fa9bd;--blue:#62b4f7;--green:#42d69a;--user:rgba(43,111,166,.26);--shadow:rgba(0,0,0,.24)}`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MAV VTC Farm Assistant Chat Log</title><style>
${palette}
*{box-sizing:border-box}html,body{min-height:100%}body{margin:0;background:var(--bg);color:var(--text);font-family:Roboto,"Segoe UI",Arial,sans-serif}.export-page{width:min(1120px,calc(100% - 32px));margin:0 auto;padding:24px 0 40px;display:grid;gap:16px}.export-meta,.chat-section{border:1px solid var(--border);border-radius:13px;background:var(--panel);overflow:hidden;box-shadow:0 8px 24px var(--shadow)}.export-meta header,.chat-section>header{padding:16px 18px;border-bottom:1px solid var(--border)}.export-meta h1{margin:0;font-size:20px}.micro{color:var(--muted);font-size:10px;margin-top:5px}.facts{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:1px;background:var(--border)}.facts>div{padding:12px;background:var(--panel)}.facts span{display:block;color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.08em}.facts strong{display:block;margin-top:5px;font-size:11px}.export-note{padding:10px 12px;border:1px solid var(--border);border-radius:9px;color:var(--muted);font-size:11px;line-height:1.5;background:var(--panel2)}.chat-messages{padding:16px 15px 20px;display:flex;flex-direction:column;gap:12px}.chat-message{max-width:100%;padding:12px 13px;border:1px solid var(--border);border-radius:12px;line-height:1.58;font-size:12px;overflow-wrap:anywhere;break-inside:avoid}.chat-message.user{margin-left:26px;background:var(--user)}.chat-message.assistant{margin-right:16px;background:var(--panel)}.chat-who{margin-bottom:6px;color:var(--blue);font-weight:800;font-size:10px;text-transform:uppercase;letter-spacing:.07em}.chat-answer{white-space:pre-wrap}.chat-meta{color:var(--muted);font-size:10px;margin-top:9px;border-top:1px solid var(--border);padding-top:7px}.chat-empty{padding:20px;color:var(--muted);text-align:center}.brand-tag{display:inline-flex;margin-top:9px;padding:3px 7px;border:1px solid color-mix(in srgb,var(--green) 55%,var(--border));border-radius:999px;color:var(--green);font-size:9px;font-weight:750}.footer-note{color:var(--muted);font-size:9px;text-align:center}
.mfe-response-meta{display:flex;gap:7px;margin:0 0 7px}.mfe-source-badge{display:inline-flex;padding:3px 7px;border:1px solid var(--border);border-radius:999px;font-size:10px;font-weight:750}.mfe-source-badge.knowledge{color:var(--green)}.mfe-source-badge.hybrid{color:#6f42c1;border-color:#b8a7e8;background:#f6f2ff}.mfe-answer-tag{display:inline-flex;margin-top:8px;padding:3px 7px;border:1px solid var(--border);border-radius:999px;font-size:9px;color:var(--muted)}.mfe-evidence{margin-top:10px;border:1px solid var(--border);border-radius:8px;padding:8px;background:var(--panel2)}.mfe-evidence summary{cursor:pointer;font-size:11px;color:var(--blue);font-weight:700}.mfe-evidence-item,.mfe-evidence-meta{font-size:10px;color:var(--muted);line-height:1.5;border-top:1px solid var(--border);padding-top:7px;margin-top:7px;white-space:pre-wrap;overflow-wrap:anywhere}
.mfe-trace-message{margin:0 16px 0 0}.mfe-interpretation-trace{overflow:hidden;border:1px solid #b8a7e8;border-radius:10px;background:#f6f2ff;color:var(--text)}.mfe-interpretation-trace>summary{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 11px;cursor:pointer;list-style:none;color:#513a8a;font-size:11px;font-weight:750}.mfe-trace-summary-main{display:inline-flex;align-items:center;gap:7px}.mfe-trace-dot{width:7px;height:7px;border-radius:50%;background:#9b7cff;box-shadow:0 0 0 3px rgba(155,124,255,.16)}.mfe-trace-summary-meta{margin-left:auto;color:var(--muted);font-size:9px}.mfe-trace-body{padding:0 11px 11px;border-top:1px solid #d9cff3}.mfe-trace-note{padding:9px 0;color:var(--muted);font-size:10px;line-height:1.45}.mfe-trace-row{display:grid;grid-template-columns:92px minmax(0,1fr);gap:10px;padding:6px 0;border-top:1px solid var(--border);font-size:10px}.mfe-trace-label{color:var(--muted);font-weight:650}.mfe-trace-value{overflow-wrap:anywhere}.mfe-trace-subdetails,.mfe-trace-block{margin-top:9px;border:1px solid var(--border);border-radius:7px;overflow:hidden;background:var(--panel)}.mfe-trace-subdetails>summary,.mfe-trace-block-title{padding:7px 9px;color:var(--muted);font-size:9px;font-weight:750;text-transform:uppercase}.mfe-trace-subdetails pre,.mfe-trace-block pre{margin:0;padding:9px;white-space:pre-wrap;overflow-wrap:anywhere;font:9px/1.45 Consolas,monospace}
@media print{body{background:#fff!important;color:#111!important}.export-page{width:100%;padding:0}.export-meta,.chat-section{box-shadow:none}.chat-message,.mfe-trace-message{break-inside:avoid}}
</style></head><body><main class="export-page"><section class="export-meta"><header><h1>MAV VTC Farm Assistant Chat Log</h1><div class="micro">Manual local export · generated in this browser · no cloud save</div><span class="brand-tag">MAV VTC Farm Troubleshooter</span></header><div class="facts"><div><span>System</span><strong>VTC Farm</strong></div><div><span>CWS Root</span><strong>${escapeHtml(cwsRoot)}</strong></div><div><span>Exported</span><strong>${escapeHtml(exported.toLocaleString())}</strong></div><div><span>AI model</span><strong>${escapeHtml(model)}</strong></div><div><span>Messages</span><strong>${ai.messages.length}</strong></div><div><span>Appearance</span><strong>${escapeHtml(theme)}</strong></div></div></section><div class="export-note">This file exists only because the operator manually chose <strong>Export</strong>. MAV VTC Farm Monitor does not automatically persist this conversation and this export was not sent to a cloud service. The saved transcript is read-only and cannot send CWS commands.</div><section class="chat-section"><header><strong>Conversation</strong></header><div class="chat-messages">${messages}</div></section><div class="footer-note">MAV VTC Farm Monitor · local browser export</div></main></body></html>`;
}
function farmCloseChatExport(){document.getElementById("mfe-chat-export-modal")?.remove();}
function farmShowChatExport(){
 farmCloseChatExport();const modal=document.createElement("div");modal.id="mfe-chat-export-modal";modal.className="mfe-export-modal";modal.innerHTML=`<section class="mfe-export-card" role="dialog" aria-modal="true"><header><div><strong>Save MAV VTC Farm Assistant Chat Log</strong><div class="mfe-export-micro">Optional local HTML export of this troubleshooting session.</div></div><button type="button" class="mfe-icon-button" data-mfe-export-close>×</button></header><div class="mfe-export-body"><div class="mfe-export-notice"><strong>Local and user initiated only.</strong><br>Nothing is uploaded to Dropbox, telemetry, a remote AI service, or any cloud destination. No file is created until you press Save.</div><div class="mfe-export-field"><label>File name</label><input id="mfe-chat-export-name" class="mfe-export-input" value="${farmChatExportFilename()}" autocomplete="off" spellcheck="false"></div><div class="mfe-export-note">The self-contained HTML includes this VTC Farm troubleshooting conversation and the response metadata captured during this browser session.</div><div id="mfe-chat-export-status" class="mfe-export-note"></div></div><footer><span class="mfe-export-micro">The saved file is read-only and cannot send commands.</span><div class="mfe-export-actions"><button type="button" class="mfe-export-button" data-mfe-export-close>Cancel</button><button type="button" id="mfe-chat-export-save" class="mfe-export-button primary">Choose Local Location & Save</button></div></footer></section>`;document.body.appendChild(modal);modal.onclick=e=>{if(e.target===modal||e.target.closest("[data-mfe-export-close]"))farmCloseChatExport();};$("#mfe-chat-export-save").onclick=farmSaveChatExport;setTimeout(()=>$("#mfe-chat-export-name")?.focus(),0);
}
async function farmSaveChatExport(){
 const status=$("#mfe-chat-export-status"),button=$("#mfe-chat-export-save");let filename=String($("#mfe-chat-export-name")?.value||farmChatExportFilename()).trim();if(!filename.toLowerCase().endsWith(".html"))filename+=".html";filename=filename.replace(/[\\/:*?"<>|]/g,"_");
 try{const blob=new Blob([farmBuildChatExportHtml()],{type:"text/html;charset=utf-8"});if(button)button.disabled=true;if(status)status.textContent="Preparing local file…";
  if(typeof window.showSaveFilePicker==="function"){try{const handle=await window.showSaveFilePicker({suggestedName:filename,types:[{description:"MAV VTC Farm HTML chat log",accept:{"text/html":[".html"]}}]});const writable=await handle.createWritable();await writable.write(blob);await writable.close();if(status)status.textContent="Saved locally. No cloud copy was created.";setTimeout(farmCloseChatExport,700);return;}catch(error){if(error?.name==="AbortError"){if(status)status.textContent="Save canceled. No file was created.";return;}}}
  const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);if(status)status.textContent="Saved through the browser download flow. No cloud copy was created.";setTimeout(farmCloseChatExport,900);
 }catch(error){if(status)status.textContent="Could not save chat log: "+String(error?.message||error);}finally{if(button&&document.body.contains(button))button.disabled=false;}
}
function exportChat(){farmShowChatExport();}

const FARM_API="/cws/vtcfarm";
const farmCommand={status:null,definition:null};
async function farmCws(path,method="GET",body=null){
 const options={method,headers:{Accept:"application/json"}};
 if(body!==null){options.headers["Content-Type"]="application/json";options.body=JSON.stringify(body);}
 const response=await fetch(FARM_API+path,options);
 const text=await response.text();let json=null;try{json=text?JSON.parse(text):null;}catch(_){throw new Error(`HTTP ${response.status}: ${text||response.statusText}`);}
 if(!response.ok)throw new Error(`HTTP ${response.status}: ${json?.Message||response.statusText}`);
 if(json&&json.Success===false)throw new Error(json.Message||"CWS command failed");
 return json;
}
function farmValue(response){return response&&Object.prototype.hasOwnProperty.call(response,"Value")?response.Value:null;}
function commandResult(value,error){const node=$("#farm-command-result");if(!node)return;node.textContent=error?`ERROR: ${error}`:JSON.stringify(value,null,2);}
async function loadFarmCommandData(){
 const statusNode=$("#farm-command-status");if(statusNode)statusNode.textContent="Loading…";
 try{
   const [status,definition]=await Promise.all([farmCws("/system/vtcfarm/status"),farmCws("/system/definition/get")]);
   farmCommand.status=farmValue(status)||{};farmCommand.definition=farmValue(definition)||{};renderFarmCommands();if(statusNode)statusNode.textContent="Live via CWS";
 }catch(error){if(statusNode)statusNode.textContent="Unavailable";commandResult(null,String(error.message||error));}
}
function arr(v){return Array.isArray(v)?v:[];}
function esc(v){return String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function renderFarmCommands(){
 const value=farmCommand.status||{};const rooms=arr(value.Rooms||value.rooms);
 const debugSelect=$("#farm-debug-room-select");if(debugSelect){const previous=debugSelect.value;debugSelect.innerHTML=rooms.map((r,i)=>{const name=r.Name||r.name||`Room ${i+1}`;return `<option value="${esc(name)}">${esc(name)}</option>`;}).join("");if(previous&&rooms.some(r=>(r.Name||r.name)===previous))debugSelect.value=previous;} const diagSelect=$("#farm-diag-room-select");if(diagSelect){const previous=diagSelect.value;diagSelect.innerHTML=rooms.map((r,i)=>{const name=r.Name||r.name||`Room ${i+1}`;return `<option value="${esc(name)}">${esc(name)}</option>`;}).join("");if(previous&&rooms.some(r=>(r.Name||r.name)===previous))diagSelect.value=previous;}
 const roomList=$("#farm-room-command-list");
 if(roomList)roomList.innerHTML=rooms.map((r,i)=>{const name=r.Name||r.name||`Room ${i+1}`,assigned=Boolean(r.CodecAssigned??r.codecAssigned),codec=r.Codec||r.codec||"";return `<div class="farm-room-command-card" data-farm-room="${esc(name)}"><div class="farm-room-command-head"><h3>${esc(name)}</h3><small>${assigned?`Codec: ${esc(codec||"assigned")}`:"No codec assigned"}</small></div><div class="farm-command-row"><button data-farm-command="reserve">Reserve</button><button data-farm-command="release" class="danger">Release</button><button data-farm-command="reroute">Re-route streams</button></div><div class="farm-command-row"><input data-farm-number placeholder="Dial number"><button data-farm-command="dial">Dial</button><button data-farm-command="hangup" class="danger">Hang up</button><button data-farm-command="answer">Answer</button></div><div class="farm-command-row"><input data-farm-dtmf placeholder="DTMF digits"><button data-farm-command="dtmf">Send DTMF</button></div><div class="farm-command-row"><button data-farm-command="presentationon">Presentation on</button><button data-farm-command="presentationoff">Presentation off</button><button data-farm-command="selfviewon">Self view on</button><button data-farm-command="selfviewoff">Self view off</button></div></div>`;}).join("")||'<div class="empty-state">No Farm rooms were returned by CWS.</div>';
 const def=farmCommand.definition||{},matrix=def.MatrixSwitcher||def.matrixSwitcher||{},sources=arr(matrix.Encoders||matrix.encoders),destinations=arr(matrix.Decoders||matrix.decoders);
 const panel=$("#farm-route-command-panel");if(panel)panel.innerHTML=`<label>Source<select id="farm-route-source">${sources.map(x=>`<option value="${esc(x.Name||x.name)}">${esc(x.Name||x.name)}</option>`).join("")}</select></label><label>Destination<select id="farm-route-destination">${destinations.map(x=>`<option value="${esc(x.Name||x.name)}">${esc(x.Name||x.name)}</option>`).join("")}</select></label><button id="farm-route-video">Route video</button>`;
}
function showFarmDiagnostic(result,consoleEquivalent){const out=$("#farm-diagnostic-output"),eq=$("#farm-diag-console-equivalent");if(eq)eq.textContent=consoleEquivalent||"";if(out)out.textContent=JSON.stringify(result,null,2);}
async function runFarmDiagnostic(room,command,body,consoleEquivalent){try{const result=await farmCws(`/${encodeURIComponent(room||"system")}/vtcfarm/${command}`,"POST",body||{});showFarmDiagnostic(result,consoleEquivalent);return result;}catch(error){showFarmDiagnostic({Success:false,Message:String(error.message||error)},consoleEquivalent);return null;}}
async function getFarmRuntimeDebug(room){const response=await farmCws(`/${encodeURIComponent(room)}/vtcfarm/diagnostics`,"POST",{});return {response,value:farmValue(response)||{}};}
function showRuntimeDebug(value,consoleEquivalent){const out=$("#farm-runtime-output"),eq=$("#farm-runtime-console-equivalent");if(eq)eq.textContent=consoleEquivalent||"";if(out)out.textContent=JSON.stringify(value,null,2);}
async function runRuntimeView(kind){const room=$("#farm-diag-room-select")?.value;if(!room)return;try{const data=await getFarmRuntimeDebug(room),root=data.value||{},debug=root.RuntimeDebugger||root.runtimeDebugger||{},iface=root.Interface||root.interface||{};if(kind==="diagnose")showRuntimeDebug(debug.AutomatedDiagnosis||debug.automatedDiagnosis||{},`vtcfarmdiagnose ${room}`);else if(kind==="trace")showRuntimeDebug(debug.Trace||debug.trace||[],`vtcfarmtrace ${room}`);else if(kind==="invariants")showRuntimeDebug(debug.Invariants||debug.invariants||[],`vtcfarminvariants ${room}`);else if(kind==="exceptions")showRuntimeDebug(debug.Exceptions||debug.exceptions||[],`vtcfarmexceptions ${room}`);else showRuntimeDebug({Interface:iface,RuntimeDebugger:debug},`vtcfarmdump ${room}`);}catch(error){showRuntimeDebug({Success:false,Message:String(error.message||error)},"runtime diagnostics");}}
async function issueFarmCommand(room,command,body={}){
 try{const result=await farmCws(`/${encodeURIComponent(room)}/vtcfarm/${command}`,"POST",body);commandResult(result);await loadFarmCommandData();}
 catch(error){commandResult(null,String(error.message||error));}
}
async function issueFarmRoute(){const source=$("#farm-route-source")?.value,destination=$("#farm-route-destination")?.value;if(!source||!destination)return;try{const result=await farmCws(`/${encodeURIComponent(destination)}/route/video`,"POST",{SourceName:source});commandResult(result);}catch(error){commandResult(null,String(error.message||error));}}
function bindFarmCommands(){
 $("#farm-command-refresh")?.addEventListener("click",loadFarmCommandData);
 $("#farm-diag-status")?.addEventListener("click",()=>runFarmDiagnostic("system","status",{},"vtcfarmstatus"));
 $("#farm-diag-room")?.addEventListener("click",()=>{const room=$("#farm-diag-room-select")?.value;if(room)runFarmDiagnostic(room,"status",{},`vtcfarmroom ${room}`);});
 $("#farm-diag-eisc")?.addEventListener("click",()=>{const room=$("#farm-diag-room-select")?.value;if(room)runFarmDiagnostic(room,"diagnostics",{},`vtcfarmeisc ${room}`);});
 $("#farm-diag-regression")?.addEventListener("click",()=>runFarmDiagnostic("system","regression",{},"vtcfarmregression"));
 $("#farm-diag-dump")?.addEventListener("click",()=>{const room=$("#farm-diag-room-select")?.value||"system";runFarmDiagnostic(room,"dump",{},room==="system"?"vtcfarmdump":`vtcfarmdump ${room}`);});
 $("#farm-diag-loglevel-apply")?.addEventListener("click",()=>{const level=$("#farm-diag-loglevel")?.value||"status";runFarmDiagnostic("system","loglevel",{Value:level},`vtcfarmloglevel ${level}`);});
 $("#farm-runtime-diagnose")?.addEventListener("click",()=>runRuntimeView("diagnose"));
 $("#farm-runtime-trace")?.addEventListener("click",()=>runRuntimeView("trace"));
 $("#farm-runtime-invariants")?.addEventListener("click",()=>runRuntimeView("invariants"));
 $("#farm-runtime-exceptions")?.addEventListener("click",()=>runRuntimeView("exceptions"));
 $("#farm-runtime-full")?.addEventListener("click",()=>runRuntimeView("full"));
 $("#farm-debug-reserve")?.addEventListener("click",()=>{const room=$("#farm-debug-room-select")?.value;if(!room)return;if(!window.confirm(`DEBUG ONLY: Simulate a legacy Reserve request from ${room}?\n\nThis will change live codec allocation state.`))return;issueFarmCommand(room,"reserve",{DebugSource:"Monitor"});});
 $("#farm-debug-release")?.addEventListener("click",()=>{const room=$("#farm-debug-room-select")?.value;if(!room)return;if(!window.confirm(`DEBUG ONLY: Simulate a legacy Release request from ${room}?\n\nThis will change live codec allocation state.`))return;issueFarmCommand(room,"release",{DebugSource:"Monitor"});});
 $("#farm-room-command-list")?.addEventListener("click",e=>{const b=e.target.closest("[data-farm-command]");if(!b)return;const card=b.closest("[data-farm-room]");if(!card)return;const room=card.dataset.farmRoom,cmd=b.dataset.farmCommand;let body={};if(cmd==="dial")body.Number=card.querySelector("[data-farm-number]")?.value||"";if(cmd==="dtmf")body.Digits=card.querySelector("[data-farm-dtmf]")?.value||"";issueFarmCommand(room,cmd,body);});
 $("#farm-route-command-panel")?.addEventListener("click",e=>{if(e.target.closest("#farm-route-video"))issueFarmRoute();});
 const commandTab=$('[data-tab="commands"]');commandTab?.addEventListener("click",()=>{if(!farmCommand.status)loadFarmCommandData();});
}

function bind(){
 addAssistantDom();applyTheme();renderSettings();bindFarmCommands();
 $("#monitor-assistant-button")?.addEventListener("click",()=>toggle(true));$("#mfe-assistant-edge")?.addEventListener("click",()=>toggle(true));$("#mfe-close-chat")?.addEventListener("click",()=>toggle(false));
 $("#mfe-send")?.addEventListener("click",()=>ask($("#mfe-ai-input").value));$("#mfe-ai-input")?.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask(e.currentTarget.value);}});
 $$(".mfe-prompt-chips button").forEach(b=>b.addEventListener("click",()=>ask(b.dataset.mfeSuggestion)));
 $("#mfe-export-chat")?.addEventListener("click",exportChat);$("#mfe-clear-chat")?.addEventListener("click",()=>{ai.messages=[];renderChat();});
 $("#mfe-settings-cards")?.addEventListener("click",async e=>{const load=e.target.closest("#mfe-load-model");if(load){load.disabled=true;try{await loadModel();}catch(_){}finally{load.disabled=false;renderSettings();}return;}const b=e.target.closest("[data-mfe-setting]");if(!b)return;settings[b.dataset.mfeSetting]=b.dataset.mfeChoice;save();if(b.dataset.mfeSetting==="aiModelTier"&&ai.generator){try{await ai.generator.dispose?.();}catch(_){}ai.generator=null;ai.selected=null;status("Model selection changed · load selected model");}});
 $("#mfe-settings-reset")?.addEventListener("click",()=>{settings={...DEFAULTS};save();});
 document.addEventListener("keydown",e=>{if(e.key==="Escape"&&ai.open)toggle(false);});
 setInterval(()=>{if(settings.appearance==="auto")applyTheme();},60000);
}
function wait(){if($("#mav-monitor"))bind();else setTimeout(wait,50);}wait();
})();
