const $=s=>document.querySelector(s);
let logCursor=0,consoleCursor=0,busy=false,cloudSyncWasRunning=false;
let sdkCursor=0,sdkPath="",sdkLines=[],sdkPollBusy=false;
let dropboxAuthPopup=null,dropboxSyncAfterAuth=false;

async function api(path,body){
  const o={cache:'no-store'};
  if(body!==undefined){o.method='POST';o.headers={'Content-Type':'application/json'};o.body=JSON.stringify(body)}
  const r=await fetch('/cws/regression/'+path,o),t=await r.text();let j;
  try{j=JSON.parse(t)}catch{throw new Error(t||('HTTP '+r.status))}
  if(!r.ok||j.Success===false)throw new Error(j.Message||('HTTP '+r.status));return j.Value;
}
function message(e){alert(e?.message||String(e))}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmtBytes(n){n=Number(n||0);if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';if(n<1073741824)return(n/1048576).toFixed(1)+' MB';return(n/1073741824).toFixed(2)+' GB'}

async function configure(){try{const v=await api('session/configure',{Address:$('#address').value,Username:$('#username').value,Password:$('#password').value,ProgramSlot:Number($('#slot').value),UseHttpsCws:$('#https').checked,AllowUntrustedHttps:$('#untrusted').checked,AllowReplaceWithoutRecoverableCpz:$('#labOverride').checked,RunMode:$('#mode').value,TestProfile:$('#targetProfile').value});renderState(v);$('#targetConsole').textContent+='\n[configured] '+$('#address').value+' Program '+$('#slot').value}catch(e){message(e)}}
async function scan(){try{$('#slotOutput').textContent='Scanning…';const v=await api('target/slots',{});$('#slotOutput').textContent=`Controller slot: ${v.ControllerSlot}\nSelf target: ${v.SelfTarget}\n\n${v.Raw||''}`}catch(e){$('#slotOutput').textContent='FAILED: '+e.message}}

function bytesToBase64(bytes){let bin='';const step=0x8000;for(let i=0;i<bytes.length;i+=step)bin+=String.fromCharCode.apply(null,bytes.subarray(i,Math.min(i+step,bytes.length)));return btoa(bin)}
async function uploadOne(kind,file){await api('upload/start',{Kind:kind,FileName:file.name,Size:file.size});const chunkSize=256*1024;let idx=0;for(let offset=0;offset<file.size;offset+=chunkSize){const b=new Uint8Array(await file.slice(offset,offset+chunkSize).arrayBuffer());await api('upload/chunk',{Kind:kind,Index:idx++,Base64:bytesToBase64(b)});$('#phase').textContent=`Uploading ${file.name}: ${Math.min(100,Math.round((offset+b.length)/file.size*100))}%`}}
async function upload(){if(jsonDirty&&!confirm('Discard unsaved JSON edits and stage a different local configuration?'))return;const cpz=$('#cpz').files[0],cfg=$('#config').files[0];if(!cpz||!cfg)return alert('Select both the CPZ and JSON configuration.');try{busy=true;await uploadOne('cpz',cpz);await uploadOne('config',cfg);await api('upload/complete',{});const p=await api('package/analyze',{});renderPackage(p);await loadStagedJson(true)}catch(e){message(e)}finally{busy=false}}

function renderPackage(p){if(!p)return;$('#packageCard').className='package';const type=p.PackageTypeName||({0:'Unknown',1:'Room',2:'VTC Farm'}[p.PackageType]||p.PackageType);$('#packageCard').innerHTML=`<strong>${esc(type)}</strong> · ${esc(p.SystemName||'Unnamed system')}<br><small>${esc(p.DetectionReason||'')}</small><br><code>CPZ ${esc((p.CpzSha256||'').slice(0,20))}…</code><br><code>CFG ${esc((p.ConfigSha256||'').slice(0,20))}…</code>`;$('#summaryPackage').textContent=type;$('#summaryPackageDetail').textContent=p.SystemName||'Analyzed package'}

function setSource(source){const cloud=source==='cloud',offline=source==='offline',local=source==='local';$('#tabCloud').classList.toggle('active',cloud);$('#tabOffline').classList.toggle('active',offline);$('#tabLocal').classList.toggle('active',local);$('#cloudSource').classList.toggle('active',cloud);$('#offlineSource').classList.toggle('active',offline);$('#localSource').classList.toggle('active',local)}

function showDropboxModal(show){$('#dropboxAuthModal').hidden=!show;if(show){$('#dropboxAuthCode').value='';setTimeout(()=>$('#dropboxAuthCode').focus(),30)}}
async function beginDropboxAuth(syncAfter=false){dropboxSyncAfterAuth=syncAfter;try{dropboxAuthPopup=window.open('about:blank','MAVDropboxAuthorization');const a=await api('cloud/auth/start',{});$('#dropboxAuthSession').value=a.SessionId||'';$('#reopenDropboxAuth').href=a.AuthorizeUrl;$('#dropboxAuthFeedback').textContent='Authorization session expires '+new Date(a.ExpiresUtc).toLocaleTimeString()+'. Paste the single-use code Dropbox displays.';if(dropboxAuthPopup){try{dropboxAuthPopup.location.href=a.AuthorizeUrl}catch{}}else{$('#dropboxAuthFeedback').textContent='Your browser blocked the new tab. Use “Open Dropbox again”, then paste the code here.'}showDropboxModal(true);await refreshCloud()}catch(e){if(dropboxAuthPopup)try{dropboxAuthPopup.close()}catch{};message(e)}}
async function completeDropboxAuth(){const code=$('#dropboxAuthCode').value.trim(),session=$('#dropboxAuthSession').value;if(!code)return $('#dropboxAuthFeedback').textContent='Paste the authorization code Dropbox displayed.';try{$('#submitDropboxAuth').disabled=true;$('#dropboxAuthFeedback').textContent='Exchanging authorization code…';await api('cloud/auth/complete',{SessionId:session,Code:code});showDropboxModal(false);await refreshCloud();if(dropboxSyncAfterAuth){dropboxSyncAfterAuth=false;await syncCloud()}}catch(e){const msg=e.message||String(e);$('#dropboxAuthFeedback').textContent=msg+(msg.includes('NameResolution')||msg.toLowerCase().includes('resolve')?' · The processor appears to be offline. Cancel and use Offline Bundle or Local Upload; no regression features are lost.':'')}finally{$('#submitDropboxAuth').disabled=false}}
async function disconnectDropbox(){if(!confirm('Remove the stored Dropbox authorization from this Regression Controller?'))return;try{await api('cloud/auth/disconnect',{});await refreshCloud()}catch(e){message(e)}}
async function syncCloud(){try{const auth=await api('cloud/auth/status');if(!auth.Authorized)return beginDropboxAuth(true);await api('cloud/sync',{});cloudSyncWasRunning=true;await refreshCloud()}catch(e){showCloudUnavailable(e)}}
async function refreshCloud(){try{const c=await api('cloud/status');renderCloud(c)}catch(e){showCloudUnavailable(e)}}
function renderCloud(c){if(!c)return;const auth=c.Authorization||{},authChip=$('#dropboxAuthChip');
  if(auth.AppKeyConfigured===false){authChip.textContent='Privacy disabled';authChip.className='chip dirty';$('#connectDropbox').textContent='Cloud disabled';$('#connectDropbox').disabled=true;$('#disconnectDropbox').disabled=true;$('#syncCloud').disabled=true;$('#stageCloud').disabled=true;$('#cloudCpz').disabled=true;$('#cloudConfig').disabled=true;$('#cloudStatusChip').textContent='Public demo';$('#cloudStatusChip').className='chip dirty';$('#cloudMeta').textContent='Cloud CurrentBuild is intentionally disabled in the public demonstration build because the Dropbox application key was removed for privacy. Offline Bundle and Local Upload remain fully functional.';populateCloudSelect($('#cloudCpz'),[],'Disabled for privacy…');populateCloudSelect($('#cloudConfig'),[],'Disabled for privacy…');return;}
  authChip.textContent=auth.Authorized?'Dropbox authorized':auth.AuthorizationPending?'Code pending':'Not authorized';authChip.className='chip '+(auth.Authorized?'valid':auth.AuthorizationPending?'dirty':'neutral');$('#connectDropbox').textContent=auth.Authorized?'Reconnect Dropbox':'Connect Dropbox';$('#disconnectDropbox').disabled=!auth.Authorized;
  const chip=$('#cloudStatusChip');if(c.SyncRunning){chip.textContent='Syncing inventory…';chip.className='chip';cloudSyncWasRunning=true}else if(c.LastError){chip.textContent='Cloud unavailable';chip.className='chip dirty';$('#cloudMeta').textContent='Cloud is optional. Last Dropbox error: '+c.LastError+' · Offline Bundle and Local Upload remain fully available.'}else if(c.LastSyncUtc){chip.textContent='Inventory current';chip.className='chip valid';$('#cloudMeta').textContent=`Last inventory sync: ${new Date(c.LastSyncUtc).toLocaleString()} · ${c.CpzFiles?.length||0} CPZ · ${c.ConfigFiles?.length||0} JSON · selected files download when staged`}else{chip.textContent='Not synced';chip.className='chip neutral';if(auth.Authorized)$('#cloudMeta').textContent='Dropbox is authorized. Sync CurrentBuild inventory to populate the package selectors.'}
  populateCloudSelect($('#cloudCpz'),c.CpzFiles||[],auth.Authorized?'Select a CPZ…':'Authorize Dropbox first…');populateCloudSelect($('#cloudConfig'),c.ConfigFiles||[],auth.Authorized?'Select a configuration…':'Authorize Dropbox first…');
  if(cloudSyncWasRunning&&!c.SyncRunning){cloudSyncWasRunning=false;if(!c.LastError)$('#cloudMeta').textContent=`Dropbox inventory sync complete · ${c.CpzFiles?.length||0} CPZ · ${c.ConfigFiles?.length||0} JSON · files download when staged`}
}
function populateCloudSelect(el,items,placeholder){const current=el.value;el.innerHTML=`<option value="">${placeholder}</option>`+items.map(x=>`<option value="${esc(x.RelativePath)}">${esc(x.RelativePath)} · ${fmtBytes(x.Bytes)}</option>`).join('');if([...el.options].some(o=>o.value===current))el.value=current}
async function stageCloud(){if(jsonDirty&&!confirm('Discard unsaved JSON edits and stage a different cloud configuration?'))return;const cpz=$('#cloudCpz').value,cfg=$('#cloudConfig').value;if(!cpz||!cfg)return alert('Select both a cloud CPZ and configuration file.');try{const p=await api('cloud/stage',{CpzRelativePath:cpz,ConfigRelativePath:cfg});renderPackage(p);await loadStagedJson(true)}catch(e){message(e)}}

function showCloudUnavailable(e){const chip=$('#cloudStatusChip');if(chip){chip.textContent='Cloud unavailable';chip.className='chip dirty'}const meta=$('#cloudMeta');if(meta)meta.textContent='Cloud is optional and could not be reached from this processor. '+(e?.message||String(e))+' · Use Offline Bundle or Local Upload without changing the regression workflow.';console.warn('Optional cloud path unavailable:',e)}

function populateOfflineSelect(el,items,placeholder){const current=el.value;el.innerHTML=`<option value="">${placeholder}</option>`+items.map(x=>`<option value="${esc(x.RelativePath)}">${esc(x.RelativePath)} · ${fmtBytes(x.Bytes)}</option>`).join('');if([...el.options].some(o=>o.value===current))el.value=current}
function renderOffline(o){if(!o)return;const chip=$('#offlineStatusChip');if(o.LastError){chip.textContent='Import failed';chip.className='chip invalid';$('#offlineMeta').textContent='Last offline bundle error: '+o.LastError}else if(o.ImportedUtc){chip.textContent='Bundle ready';chip.className='chip valid';$('#offlineMeta').textContent=`${o.BundleFileName||'Offline bundle'} · imported ${new Date(o.ImportedUtc).toLocaleString()} · ${o.CpzFiles?.length||0} CPZ · ${o.ConfigFiles?.length||0} JSON · CP4N Internet not required`}else{chip.textContent='No bundle';chip.className='chip neutral';$('#offlineMeta').textContent='Upload a ZIP through this browser. The laptop or approved transfer process supplies the bundle; the processor remains offline.'}populateOfflineSelect($('#offlineCpz'),o.CpzFiles||[],'Select a CPZ…');populateOfflineSelect($('#offlineConfig'),o.ConfigFiles||[],'Select a configuration…')}
async function refreshOffline(){try{renderOffline(await api('offline/status'))}catch(e){console.warn(e)}}
async function importOffline(){const file=$('#offlineBundle').files[0];if(!file)return alert('Select an offline bundle ZIP.');if(jsonDirty&&!confirm('Discard unsaved JSON edits and import a different offline package?'))return;try{busy=true;await api('offline/upload/start',{FileName:file.name,Size:file.size});const chunkSize=256*1024;let idx=0;for(let offset=0;offset<file.size;offset+=chunkSize){const b=new Uint8Array(await file.slice(offset,offset+chunkSize).arrayBuffer());await api('offline/upload/chunk',{Index:idx++,Base64:bytesToBase64(b)});$('#phase').textContent=`Importing ${file.name}: ${Math.min(100,Math.round((offset+b.length)/file.size*100))}%`}renderOffline(await api('offline/upload/complete',{}))}catch(e){message(e);await refreshOffline()}finally{busy=false}}
async function stageOffline(){if(jsonDirty&&!confirm('Discard unsaved JSON edits and stage a different offline configuration?'))return;const cpz=$('#offlineCpz').value,cfg=$('#offlineConfig').value;if(!cpz||!cfg)return alert('Select both a CPZ and JSON from the offline bundle.');try{const p=await api('offline/stage',{CpzRelativePath:cpz,ConfigRelativePath:cfg});renderPackage(p);await loadStagedJson(true)}catch(e){message(e)}}

async function start(path){if(jsonDirty){message(new Error('Save or revert staged JSON edits before deployment/testing.'));return}if($('#mode').value==='full'&&!$('#confirmMaintenance').checked){message(new Error('Confirm an authorized maintenance window before running a Full Regression.'));return}try{await api(path,{MaintenanceAcknowledged:$('#confirmMaintenance').checked});await refresh()}catch(e){message(e)}}
async function refresh(){try{const s=await api('status');renderState(s)}catch(e){console.warn(e)}}
function renderState(s){if(!s)return;const statusNames={0:'Idle',1:'Uploading',2:'Ready',3:'Deploying',4:'WaitingForCws',5:'Testing',6:'Passed',7:'Warning',8:'Failed',9:'Aborted'};const st=statusNames[s.Status]||String(s.Status||'Idle');$('#globalState').textContent=st.toUpperCase();$('#globalState').className='state '+st;$('#bar').style.width=(s.Progress||0)+'%';$('#phase').textContent=(s.Phase||'')+(s.Detail?' · '+s.Detail:'');$('#phaseBadge').textContent=s.Phase||st;$('#summaryWorkflow').textContent=st;$('#summaryProgress').textContent=(s.Progress||0)+'% complete';if(s.Target){$('#summaryTarget').textContent=s.Target.Address||'Configured';$('#summarySlot').textContent='Program '+s.Target.ProgramSlot+(s.SelfTarget?' · self-target':'')}if(s.Package)renderPackage(s.Package);const c=s.Checks||[];$('#checks').innerHTML=c.length?c.map(x=>`<div class="checkResult"><span class="resultBadge ${esc(x.Status)}">${esc(x.Status)}</span><strong>${esc(x.Name)}</strong><span class="resultDetail">${esc(x.Detail||'')}${x.TargetEvidence?`<br><small>Target SDK evidence: ${x.TargetEvidence.EventsObserved} event(s), observer #${x.TargetEvidence.FromLocalSequence+1}–${x.TargetEvidence.ToLocalSequence}${x.TargetEvidence.FeedConnected?'':' · feed unavailable'}</small>`:''}</span></div>`).join(''):'<div class="empty">No checks yet.</div>';$('#logMeta').textContent=(s.LogPath||'SDK-backed session log')+(s.SelfTarget?` · self-target · controller slot ${s.ControllerSlot}`:'')}

async function pollLog(){try{const entries=await api('logs/poll',{AfterSequence:logCursor,MaxEntries:500});if(entries?.length){const host=$('#log');for(const e of entries){logCursor=Math.max(logCursor,Number(e.Sequence||0));host.textContent+=`\n${e.TimestampUtc||''} [${e.Level}] ${e.Message}`;}host.scrollTop=host.scrollHeight}}catch{}}
async function pollConsole(){try{const entries=await api('console/poll',{AfterSequence:consoleCursor,MaxEntries:500});if(entries?.length){const host=$('#targetConsole');for(const e of entries){consoleCursor=Math.max(consoleCursor,Number(e.Sequence||0));host.textContent+=`\n${e.TimestampUtc||''} [${e.Kind||'CON'}] ${e.Text||''}`;}host.scrollTop=host.scrollHeight}}catch{}}

function renderTargetSdk(){
  const filter=$('#targetSdkFilter').value.trim().toLowerCase();
  const visible=filter?sdkLines.filter(x=>x.toLowerCase().includes(filter)):sdkLines;
  const host=$('#targetSdkLog');host.textContent=visible.slice(-1500).join('\n')||'No matching target SDK events yet.';
  if($('#targetSdkAutoScroll').checked)host.scrollTop=host.scrollHeight;
}
async function refreshTargetSdk(){
  if(sdkPollBusy)return;
  sdkPollBusy=true;
  try{
    const st=await api('target-sdk/status');
    const chip=$('#targetSdkState');
    chip.textContent=!st.Active?'Stopped':st.Connected?'SDK journal live':'Waiting for CWS';
    chip.className='chip '+(st.Connected?'valid':'neutral');
    if(st.LogPath&&st.LogPath!==sdkPath){sdkPath=st.LogPath;sdkCursor=0;sdkLines=[];renderTargetSdk()}
    $('#targetSdkMeta').textContent=st.Active?`${st.Target||'Target'} · ${st.Path||''} · epoch ${st.Epoch||0} · target cursor ${st.TargetSequence||0} · observed ${st.ObservedCount||0} · ${st.LastError?'Waiting: '+st.LastError:'Last sync '+(st.LastSyncUtc?new Date(st.LastSyncUtc).toLocaleTimeString():'pending')}`:'SDK observation stopped. A regression automatically starts it.';
    if(st.Active){
      const rows=await api('target-sdk/poll',{AfterSequence:sdkCursor,MaxEntries:650});
      if(rows?.length){for(const e of rows){sdkCursor=Math.max(sdkCursor,Number(e.LocalSequence||0));sdkLines.push(`${e.ObservedUtc||''} [E${e.Epoch}/#${e.TargetSequence}] [${e.Level||'LOG'}]${e.TestStep?' ['+e.TestStep+']':''} ${e.Message||''}`)}if(sdkLines.length>5000)sdkLines=sdkLines.slice(-4500);renderTargetSdk()}
    }
  }catch(e){$('#targetSdkState').textContent='Observer unavailable';$('#targetSdkState').className='chip invalid';$('#targetSdkMeta').textContent=e.message||String(e)}
  finally{sdkPollBusy=false}
}
async function connectTargetSdk(){try{await api('target-sdk/connect',{});await refreshTargetSdk()}catch(e){message(e)}}
async function disconnectTargetSdk(){try{await api('target-sdk/disconnect',{});await refreshTargetSdk()}catch(e){message(e)}}

async function refreshConsoleStatus(){try{const s=await api('console/status');const el=$('#consoleState');el.textContent=s.Connected?'Connected':'Disconnected';el.className='chip '+(s.Connected?'':'neutral');if(s.Connected&&s.Target)el.title='Connected to '+s.Target}catch{}}
async function connectConsole(){try{await api('console/connect',{});await refreshConsoleStatus();await pollConsole()}catch(e){message(e)}}
async function disconnectConsole(){try{await api('console/disconnect',{});await refreshConsoleStatus()}catch(e){message(e)}}

async function sendConsole(command){const cmd=(command??$('#consoleCommand').value).trim();if(!cmd)return;try{await api('console/send',{Command:cmd});$('#consoleCommand').value='';await pollConsole()}catch(e){message(e)}}
async function sendPreset(name){if(name==='kill'&&!confirm(`Stop Program ${$('#slot').value} on the configured target?`))return;if(name==='load'&&!confirm(`Issue PROGLOAD for Program ${$('#slot').value} on the configured target?`))return;try{await api('console/preset',{Preset:name});await pollConsole()}catch(e){message(e)}}
async function clearConsole(){try{await api('console/clear',{});consoleCursor=0;$('#targetConsole').textContent='Target console cleared.'}catch(e){message(e)}}

async function downloadText(route,fileName){try{const r=await fetch('/cws/regression/'+route,{cache:'no-store'}),t=await r.text(),blob=new Blob([t],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=fileName;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)}catch(e){message(e)}}
const stamp=()=>new Date().toISOString().replace(/[:.]/g,'-');

$('#exportReport').addEventListener('click',()=>downloadText('evidence/report','MAV-Regression-Report-'+stamp()+'.json'));$('#configure').addEventListener('click',configure);$('#scan').addEventListener('click',scan);$('#upload').addEventListener('click',upload);$('#tabCloud').addEventListener('click',()=>setSource('cloud'));$('#tabOffline').addEventListener('click',()=>setSource('offline'));$('#tabLocal').addEventListener('click',()=>setSource('local'));$('#importOffline').addEventListener('click',importOffline);$('#refreshOffline').addEventListener('click',refreshOffline);$('#stageOffline').addEventListener('click',stageOffline);$('#connectDropbox').addEventListener('click',()=>beginDropboxAuth(false));$('#disconnectDropbox').addEventListener('click',disconnectDropbox);$('#syncCloud').addEventListener('click',syncCloud);$('#refreshCloud').addEventListener('click',refreshCloud);$('#stageCloud').addEventListener('click',stageCloud);$('#submitDropboxAuth').addEventListener('click',completeDropboxAuth);$('#cancelDropboxAuth').addEventListener('click',()=>showDropboxModal(false));$('#closeDropboxAuth').addEventListener('click',()=>showDropboxModal(false));$('#dropboxAuthCode').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();completeDropboxAuth()}});
$('#deployTest').addEventListener('click',()=>{if(!$('#confirmDestructive').checked)return alert('Confirm the deployment actions before starting Deploy + Full Workflow.');start('workflow/deploy-test')});$('#testOnly').addEventListener('click',()=>start('workflow/test-only'));$('#abort').addEventListener('click',()=>start('workflow/abort'));$('#refresh').addEventListener('click',refresh);
$('#consoleForm').addEventListener('submit',e=>{e.preventDefault();sendConsole()});$('#connectConsole').addEventListener('click',connectConsole);$('#disconnectConsole').addEventListener('click',disconnectConsole);document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>sendPreset(b.dataset.preset)));$('#clearConsole').addEventListener('click',clearConsole);$('#exportConsole').addEventListener('click',()=>downloadText('console/export','MAV-Target-Console-'+stamp()+'.log'));$('#exportLog').addEventListener('click',()=>downloadText('logs/export','MAV-Regression-'+stamp()+'.log'));
$('#connectTargetSdk').addEventListener('click',connectTargetSdk);
$('#disconnectTargetSdk').addEventListener('click',disconnectTargetSdk);
$('#exportTargetSdk').addEventListener('click',()=>downloadText('target-sdk/export','MAV-Target-SDK-'+stamp()+'.jsonl'));
$('#exportCombined').addEventListener('click',()=>downloadText('evidence/combined','MAV-Combined-Regression-'+stamp()+'.log'));
$('#targetSdkFilter').addEventListener('input',renderTargetSdk);
setInterval(()=>{if(!busy){refresh();pollLog();pollConsole();refreshCloud();refreshOffline();refreshConsoleStatus();refreshTargetSdk()}},1300);refresh();refreshCloud();refreshOffline();refreshConsoleStatus();pollLog();pollConsole();refreshTargetSdk();


// Configuration editing lives ONLY on the Regression Controller staged copy.
let jsonOriginal='',jsonHash='',jsonDirty=false,jsonLoadedHash='',jsonPreviewTimer=0,jsonLoadRunning=false;
const editor=$('#jsonEditor'), editorStatus=$('#jsonStatus'), feedback=$('#jsonFeedback');
function editorNote(text,kind=''){feedback.textContent=text;feedback.className='editorFeedback '+kind;}
function markJson(dirty,valid){jsonDirty=dirty;editorStatus.textContent=!jsonHash?'No staged JSON':dirty?(valid?'Unsaved edits':'Invalid / unsaved'):'Staged / saved';editorStatus.className='chip '+(!jsonHash?'neutral':dirty?(valid?'dirty':'invalid'):'valid');$('#jsonSave').disabled=!dirty||!valid;$('#deployTest').disabled=dirty;}
function jsonSyntax(source){let result='',last=0;const token=/"(?:\\.|[^"\\])*"\s*(?=:)|"(?:\\.|[^"\\])*"|\b(?:true|false|null|-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)\b/g;let m;while((m=token.exec(source))){result+=esc(source.slice(last,m.index));const raw=m[0],kind=raw.startsWith('"')?(source.slice(token.lastIndex).trimStart().startsWith(':')?'key':'str'):raw==='true'||raw==='false'?'bool':raw==='null'?'null':'num';result+='<span class="'+kind+'">'+esc(raw)+'</span>';last=token.lastIndex}return result+esc(source.slice(last))}
function updateJsonPreview(){const text=editor.value;$('#jsonLines').textContent=Array.from({length:Math.min(10000,text.split('\n').length)},(_,i)=>i+1).join('\n');$('#editorSize').textContent=fmtBytes(new TextEncoder().encode(text).length);$('#jsonPreview').innerHTML=jsonSyntax(text||'No JSON loaded.');let ok=false;try{if(text.trim()&&!(JSON.parse(text) instanceof Array)&&typeof JSON.parse(text)==='object'){ok=true;editorNote(text!==jsonOriginal?'Valid local JSON. Save to staging before deploying.':'Valid staged JSON.','ok')}else throw Error('Root must be a JSON object.')}catch(e){if(jsonHash)editorNote(e.message,'error');else editorNote('Load a staged configuration first.');}markJson(text!==jsonOriginal&&!!jsonHash,ok);}
async function loadStagedJson(force=false){if(jsonLoadRunning)return;if(jsonDirty&&!force){if(!confirm('Discard unsaved edits and reload the staged JSON?'))return;}jsonLoadRunning=true;try{const d=await api('package/config/get');jsonOriginal=d.JsonText||'';jsonHash=d.ConfigSha256||'';jsonLoadedHash=jsonHash;editor.value=jsonOriginal;$('#editorFile').textContent=d.FileName||'SystemDefinition.json';updateJsonPreview();editorNote('Loaded staged JSON · SHA-256 '+jsonHash.slice(0,18)+'…','ok');$('#jsonStatus').textContent='Staged / saved';$('#jsonStatus').className='chip valid'}catch(e){jsonHash='';$('#jsonStatus').textContent='JSON handoff failed';$('#jsonStatus').className='chip invalid';editorNote('Package staged, but configuration workspace could not open the staged JSON: '+(e.message||e),'error');message(e)}finally{jsonLoadRunning=false}}
async function validateJson(){try{const text=editor.value;const data=JSON.parse(text);if(!data||Array.isArray(data)||typeof data!=='object')throw Error('Root must be a JSON object.');const r=await api('package/config/validate',{JsonText:text});updateJsonPreview();editorNote('Validated on controller · '+(r.Name||'Unnamed system')+' · '+r.Properties+' root fields · '+fmtBytes(r.Bytes),'ok')}catch(e){editorNote(e.message,'error');markJson(editor.value!==jsonOriginal,false)}}
async function saveJson(){try{if(!jsonHash)throw Error('Stage JSON before editing.');const data=JSON.parse(editor.value);if(!data||Array.isArray(data)||typeof data!=='object')throw Error('Root must be a JSON object.');const r=await api('package/config/save',{JsonText:editor.value,ExpectedSha256:jsonHash});jsonHash=r.ConfigSha256;jsonOriginal=r.JsonText;editor.value=jsonOriginal;jsonLoadedHash=jsonHash;updateJsonPreview();editorNote('Saved to controller staging, not to target. Previous copy preserved. SHA-256 '+jsonHash.slice(0,18)+'…','ok');await refresh();}catch(e){editorNote(e.message,'error')}}
function exportJson(){if(!editor.value)return;const blob=new Blob([editor.value],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='MAV-Staged-SystemDefinition-'+stamp()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
editor.addEventListener('input',()=>{clearTimeout(jsonPreviewTimer);jsonPreviewTimer=setTimeout(updateJsonPreview,120)});
editor.addEventListener('scroll',()=>{$('#jsonLines').scrollTop=editor.scrollTop});
editor.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const i=editor.selectionStart;editor.setRangeText('  ',i,editor.selectionEnd,'end');editor.dispatchEvent(new Event('input'))}});
$('#jsonLoad').addEventListener('click',()=>loadStagedJson());$('#jsonFormat').addEventListener('click',()=>{try{const v=JSON.parse(editor.value);if(!v||Array.isArray(v)||typeof v!=='object')throw Error('Root must be a JSON object.');editor.value=JSON.stringify(v,null,2)+'\n';updateJsonPreview()}catch(e){editorNote(e.message,'error')}});
$('#jsonValidate').addEventListener('click',validateJson);$('#jsonRevert').addEventListener('click',()=>{editor.value=jsonOriginal;updateJsonPreview();editorNote('Unsaved edits reverted.','ok')});$('#jsonSave').addEventListener('click',saveJson);$('#jsonDownload').addEventListener('click',exportJson);
$('#siteTheme').addEventListener('change',e=>{document.body.dataset.siteTheme=e.target.value});$('#editorAppearance').addEventListener('change',e=>{document.body.dataset.editorAppearance=e.target.value});
// A status poll must never erase an unsaved editing session; load once when a new config SHA is staged.
const baseRenderPackage=renderPackage;
renderPackage=function(p){baseRenderPackage(p);if(p&&p.ConfigSha256&&p.ConfigSha256!==jsonLoadedHash&&!jsonDirty&&!jsonLoadRunning){loadStagedJson(true)}};
updateJsonPreview();
